version: 2.1

defaults: &defaults
  docker :
    - image: aquasec/trivy-ci:latest
  environment:
    CGO_ENABLED: "0"

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: login to Docker Hub
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: login to GitHub Container Registry
          command: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin
      - run:
          name: Release
          command: goreleaser --rm-dist
      - run:
          name: Clone trivy repository
          command: git clone git@github.com:aquasecurity/trivy-repo.git
      - run:
          name: Setup git settings
          command: |
            git config --global user.email "knqyf263@gmail.com"
            git config --global user.name "Teppei Fukuda"
      - run:
          name: Create rpm repository
          command: ci/deploy-rpm.sh
      - run:
          name: Import GPG key
          command: echo -e "$GPG_KEY" | gpg --import
      - run:
          name: Create deb repository
          command: ci/deploy-deb.sh

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
